### ISSUE TITLE
representative region simulation

### ISSUE THREAD

**Issue by i-riyad** [trevorcarlson/barrierpoint#2]
In the run_sniper() function of barrierpoint.py script, at line 247, I can see that the ex_log() call is commented out. Is it because of the case that sniper is unable to run multi-threaded pinballs, as the TODO comments above suggest?
When I let the ex_log() function to execute, I can see from the output log that sniper simulates the representative regions, though at some point I get the exception pasted below. Can you please explain a bit what actually we expect from this ex_log() call and what we are getting now?

Exception at ex_log():
Traceback (most recent call last):
  File "/home/riyad/mtcbsp/sniper-6.1/run-sniper", line 883, in <module>
    gen_simout.generate_simout(resultsdir = outputdir, output = open(os.path.join(outputdir, 'sim.out'), 'w'), silent = True)
  File "/home/riyad/mtcbsp/sniper-6.1/tools/gen_simout.py", line 61, in generate_simout
    for c in range(ncores)
ZeroDivisionError: float division by zero

Thanks

**Comment by trevorcarlson** [comment]
@riyadshairi979 multi-threaded pinballs might work, but might not (they haven't been tested thoroughly), and I would not recommend running Sniper with MT pinballs or relying on the results of these runs.

The basic issue is that Sniper would like to control application timing through microarchitectural events, but PinPlay wants to enforce reproducible replay and control timing as well. Of course, this cannot work in practice, as only one component should control execution. We'd ultimately like to have Sniper control execution because the point is to determine application runtime.

The error you are seeing is the result of gen_simout.py failing to generate the sim.out file because Sniper did not run correctly. This is probably a result of the situation that I am describing above.

There are two issues currently. One is correctly injecting the warmed up state of the run, and the other is correctly handling any other mutex state and allowing Sniper to control the thread ordering.

One way that I have been thinking about implementing this in Sniper is with a user-space checkpointing scheme, like [CRIU](http://criu.org) or [DMTCP](http://dmtcp.sourceforge.net). One scenario would be to execute the application, collecting warmup data for use in Sniper. Then when we reach the correct barrier location, we can snapshot the application for later use. When we'd like to replay this application, we would restore the snapshot, inject/replay the cache state into Sniper and then run execution as normal.

**Comment by i-riyad** [comment]
If that's the case how did you constructed the whole program runtime in barrierpoint paper? According to section C of chapter [3](http://users.elis.ugent.be/~leeckhou/papers/ispass2014.pdf), detailed simulation of each barrierpoint is performed. Did you use sniper to do that? Or did you performed those representative region simulation with some "predefined assumption" etc. in sniper?

**Comment by trevorcarlson** [comment]
@riyadshairi979 All timing simulations were done in Sniper. To validate the methodology, I ran the applications up to each barrier point (with either a full warmup for validation or injected the warmup LRU state given the warmup methodology described in the paper). To accomplish this, I wrote a custom update to the SIFT recorder to fast-forward based on barrier count and collect the warmup state. This version of the recorder required extensive changes to the recorder, and the code quality could be improved which is why I did not include it in the current version of Sniper. I did not use PinPlay during timing simulation, but did use it up-front when I collected traces for evaluating the applications for similarity. I developed this version of the methodology to try and use PinPlay as a way forward, but was not able to get coming working with this version.

What I have released here is the PinPlay methodology for workload analysis. In the paper, I then used Sniper for simulation and evaluation based on this analysis. Performance speedup numbers combine the time to inject the warmup state and playback the detailed simulation. Unfortunately, user-space checkpointing was not stable at that time, and therefore I could not produce a methodology that would allow this to work out-of-the-box. I released these scripts to provide a starting point for others interested in using the work.

That said, I would love to develop a methodology that would provide a user-space BarrierPoint implementation that allows for simulation speedup (which is why I referenced CRIU and DMTCP above). On the other hand, it should is possible to update Sniper today to run in warm up to the barrier point of interest, and execute that, but the speedup there might be limited by the functional warmup required for each barrier point.

Definitely tell me if you have any other questions or need any other clarifications on this work and I will be glad to help where I can.
